services:
  db:
    image: postgres:16
    container_name: musicplayer-postgres
    environment:
      POSTGRES_DB: musicplayer
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicuser -d musicplayer"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicplayer-backend
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_URL: jdbc:postgresql://db:5432/musicplayer
      DB_USER: musicuser
      DB_PASSWORD: musicpass

      JWT_SECRET: cOUtd+iZ5rwAF7aOoB3FGFz8y+rvCTEdJbKqek8EjSw=
      JWT_EXPIRATION: 86400000

      KEYCLOAK_REALM: music-player
      KEYCLOAK_INTERNAL_URL: http://host.docker.internal:8081
      KEYCLOAK_ISSUER_URI: http://localhost:8081/realms/music-player
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8081/realms/music-player/protocol/openid-connect/certs

      KEYCLOAK_CLIENT_ID: music-player-backend
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

      KEYCLOAK_ADMIN_CLIENT_ID: music-player-admin
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

      MAIL_HOST: smtp.seznam.cz
      MAIL_PORT: 465
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_USERNAME}
      APP_EMAIL_USE: true

      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_PATH_RESET_PASSWORD: ${FRONTEND_PATH_RESET_PASSWORD}
      FRONTEND_PATH_VERIFY_EMAIL: ${FRONTEND_PATH_VERIFY_EMAIL}
    ports:
      - "8080:8080"

volumes:
  postgres_data: