spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/musicplayer}
spring.datasource.username=${DB_USER:musicuser}
spring.datasource.password=${DB_PASSWORD:musicpass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
# for local development, should be overridden in production
jwt.secret=${JWT_SECRET:cOUtd+iZ5rwAF7aOoB3FGFz8y+rvCTEdJbKqek8EjSw=}
jwt.expiration=${JWT_EXPIRATION:86400000}
spring.cache.type=jcache
bucket4j.enabled=true
bucket4j.cache-to-use=jcache
bucket4j.methods[0].name=default-api
bucket4j.methods[0].cache-name=buckets
bucket4j.methods[0].rate-limit.bandwidths[0].capacity=60
bucket4j.methods[0].rate-limit.bandwidths[0].time=60
bucket4j.methods[0].rate-limit.bandwidths[0].unit=seconds
bucket4j.methods[0].rate-limit.bandwidths[0].refill-speed=greedy
bucket4j.methods[1].name=login-strict
bucket4j.methods[1].cache-name=buckets
bucket4j.methods[1].rate-limit.bandwidths[0].capacity=3
bucket4j.methods[1].rate-limit.bandwidths[0].time=60
bucket4j.methods[1].rate-limit.bandwidths[0].unit=seconds
bucket4j.methods[1].rate-limit.bandwidths[0].refill-speed=greedy
bucket4j.methods[2].name=register-strict
bucket4j.methods[2].cache-name=buckets
bucket4j.methods[2].rate-limit.bandwidths[0].capacity=2
bucket4j.methods[2].rate-limit.bandwidths[0].time=30
bucket4j.methods[2].rate-limit.bandwidths[0].unit=seconds
bucket4j.methods[2].rate-limit.bandwidths[0].refill-speed=interval
bucket4j.methods[3].name=create-api
bucket4j.methods[3].cache-name=buckets
bucket4j.methods[3].rate-limit.bandwidths[0].capacity=5
bucket4j.methods[3].rate-limit.bandwidths[0].time=100
bucket4j.methods[3].rate-limit.bandwidths[0].unit=seconds
bucket4j.methods[3].rate-limit.bandwidths[0].refill-speed=greedy
spring.cache.jcache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
spring.cache.cache-names=buckets