-- Drop all existing tables in the correct order
DROP TABLE IF EXISTS group_tracks;
DROP TABLE IF EXISTS user_track_shares;
DROP TABLE IF EXISTS user_group_shares;
DROP TABLE IF EXISTS user_tracks;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS track_windows;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;

-- Create tables in the correct order
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_group_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name VARCHAR(255) NOT NULL,
    track_link VARCHAR(255) NOT NULL,
    duration INTEGER NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_track_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE track_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    position_from BIGINT NOT NULL,
    position_to BIGINT NOT NULL,
    fade_in BOOLEAN NOT NULL,
    fade_out BOOLEAN NOT NULL,
    CONSTRAINT fk_point_window FOREIGN KEY (track_id) REFERENCES tracks(id)
);

CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    selected_track_id BIGINT,
    name VARCHAR(255),
    volume INTEGER,
    repeat BOOLEAN,
    overplay BOOLEAN,
    CONSTRAINT fk_board_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_board_track FOREIGN KEY (selected_track_id) REFERENCES tracks(id)
);

-- Group <-> Track (Many-to-Many)
CREATE TABLE group_tracks (
    group_id BIGINT NOT NULL,
    track_id BIGINT NOT NULL,
    CONSTRAINT pk_group_tracks PRIMARY KEY (group_id, track_id),
    CONSTRAINT fk_gt_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_gt_track FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);

-- ManyToMany join tables
CREATE TABLE user_tracks (
    user_id BIGINT NOT NULL,
    track_id BIGINT NOT NULL,
    CONSTRAINT pk_user_tracks PRIMARY KEY (user_id, track_id),
    CONSTRAINT fk_ut_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ut_track FOREIGN KEY (track_id) REFERENCES tracks(id)
);

CREATE TABLE user_groups (
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT pk_user_groups PRIMARY KEY (user_id, group_id),
    CONSTRAINT fk_ug_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ug_group FOREIGN KEY (group_id) REFERENCES groups(id)
);

-- Share tables
CREATE TABLE user_track_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    track_id BIGINT NOT NULL,
    CONSTRAINT fk_track_share_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_track_share_track FOREIGN KEY (track_id) REFERENCES tracks(id)
);

CREATE TABLE user_group_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_group_share_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_group_share_group FOREIGN KEY (group_id) REFERENCES groups(id)
);

-- Create indices
CREATE INDEX idx_track_owner ON tracks(owner_id);
CREATE INDEX idx_group_owner ON groups(owner_id);
CREATE INDEX idx_board_owner ON boards(owner_id);
CREATE INDEX idx_board_track ON boards(selected_track_id);

CREATE INDEX idx_gt_group ON group_tracks(group_id);
CREATE INDEX idx_gt_track ON group_tracks(track_id);

CREATE INDEX idx_track_share_user ON user_track_shares(user_id);
CREATE INDEX idx_track_share_track ON user_track_shares(track_id);
CREATE INDEX idx_group_share_user ON user_group_shares(user_id);
CREATE INDEX idx_group_share_group ON user_group_shares(group_id);
