CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,

    CONSTRAINT fk_sessions_owner
        FOREIGN KEY (owner_id)
        REFERENCES users(id)
);

ALTER TABLE boards
ADD COLUMN session_id BIGINT;

INSERT INTO sessions (name, description, owner_id)
SELECT
    'Default session',
    'Automatically created session for existing boards',
    b.owner_id
FROM boards b
GROUP BY b.owner_id;

UPDATE boards b
SET session_id = s.id
FROM sessions s
WHERE s.owner_id = b.owner_id
  AND s.name = 'Default session'
  AND b.session_id IS NULL;

ALTER TABLE boards
ALTER COLUMN session_id SET NOT NULL;

ALTER TABLE boards
ADD CONSTRAINT fk_boards_session
    FOREIGN KEY (session_id)
    REFERENCES sessions(id);